[secrets]
TWELVE_DATA_API_KEY = "010b5dc49d784e548e99c2f6da02a266"
BINANCE_API_KEY = "QhZbUZLk84RU4T6sCqgzHmWjyrLqwdxaV40TokxKVZuZXEUfxfi2aeKDBvBkll8U"
BINANCE_SECRET_KEY = "pobmPuSnJeLVrZmruHQ6yu1f4HcD8HVO1wUoR1tVSIGLnUInmKYbuKgbcupsk2Vr"
EMAIL_USER = "your_email@example.com"
EMAIL_PASSWORD = "your_email_password"